feat: protobuf
kardiachain/rust-kardia pull request #6
Opened 2022-07-27 05:10 UTC by phatngluu

2022-07-29 08:42 UTC, lewtran requested changes
The protobuf package should be named "proto" or "protobuf" instead of "pb".
It improves the readability while maintaining the code

2022-07-29 08:48 UTC, phatngluu commented
> The protobuf package should be named "proto" or "protobuf" instead of "pb".
> It improves the readability while maintaining the code

I changed to `proto`

2022-08-01 03:09 UTC, lewtran approved these changes

2022-08-01 03:09 UTC, lewtran commented
LGTM

2022-08-01 03:10 UTC, merged